<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTXs4Fq1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTXs4Fq1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTXs4Fq1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTXs4Fq1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTXs4Fq1\App_KernelDevDebugContainer([
    'container.build_hash' => 'TXs4Fq1',
    'container.build_id' => '34998c89',
    'container.build_time' => 1785934682,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTXs4Fq1');
