version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "build/1.1.3"

  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: "weekly"
    target-branch: "build/1.1.3"

  - package-ecosystem: composer
    directory: "/web"
    schedule:
      interval: "weekly"
    target-branch: "build/1.1.3"

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: "weekly"
    target-branch: "build/1.1.3"
