<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260910184845 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, theme_name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, project_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68DB3CCC6C1197C9 ON project_content (project_id_id)');
        $this->addSql('CREATE TABLE project_content_project_media (project_content_id INT NOT NULL, project_media_id INT NOT NULL, PRIMARY KEY (project_content_id, project_media_id))');
        $this->addSql('CREATE INDEX IDX_64ECD3C99C06D8DF ON project_content_project_media (project_content_id)');
        $this->addSql('CREATE INDEX IDX_64ECD3C9D7D156AE ON project_content_project_media (project_media_id)');
        $this->addSql('CREATE TABLE project_content_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(191) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE project_content ADD CONSTRAINT FK_68DB3CCC6C1197C9 FOREIGN KEY (project_id_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_content_project_media ADD CONSTRAINT FK_64ECD3C99C06D8DF FOREIGN KEY (project_content_id) REFERENCES project_content (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_content_project_media ADD CONSTRAINT FK_64ECD3C9D7D156AE FOREIGN KEY (project_media_id) REFERENCES project_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD role VARCHAR(255) DEFAULT NULL');
        $this->addSql('UPDATE project SET role = \'\' WHERE role IS NULL');
        $this->addSql('ALTER TABLE project ALTER COLUMN role SET NOT NULL');
        $this->addSql('ALTER TABLE project ADD intro TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_content DROP CONSTRAINT FK_68DB3CCC6C1197C9');
        $this->addSql('ALTER TABLE project_content_project_media DROP CONSTRAINT FK_64ECD3C99C06D8DF');
        $this->addSql('ALTER TABLE project_content_project_media DROP CONSTRAINT FK_64ECD3C9D7D156AE');
        $this->addSql('DROP TABLE project_content');
        $this->addSql('DROP TABLE project_content_project_media');
        $this->addSql('DROP TABLE project_content_translations');
        $this->addSql('ALTER TABLE project DROP role');
        $this->addSql('ALTER TABLE project DROP intro');
    }
}
