<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902134752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hard_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, image_url VARCHAR(500) DEFAULT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9EE9EE46C54C8C93 ON hard_skill (type_id)');
        $this->addSql('CREATE TABLE hard_skill_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE hard_skill ADD CONSTRAINT FK_9EE9EE46C54C8C93 FOREIGN KEY (type_id) REFERENCES hard_skill_type (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE hard_skill DROP CONSTRAINT FK_9EE9EE46C54C8C93');
        $this->addSql('DROP TABLE hard_skill');
        $this->addSql('DROP TABLE hard_skill_type');
    }
}
