<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903110237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type INT NOT NULL, url VARCHAR(300) NOT NULL, project_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7979A8926C1197C9 ON project_media (project_id_id)');
        $this->addSql('ALTER TABLE project_media ADD CONSTRAINT FK_7979A8926C1197C9 FOREIGN KEY (project_id_id) REFERENCES project (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_media DROP CONSTRAINT FK_7979A8926C1197C9');
        $this->addSql('DROP TABLE project_media');
    }
}
