<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902204400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project ADD slug VARCHAR(255)');

        $this->addSql("
            UPDATE project
            SET slug = LOWER(
                REGEXP_REPLACE(
                    TRIM(name),
                    '[^a-zA-Z0-9]+',
                    '-',
                    'g'
                )
            )
            WHERE slug IS NULL
        ");
        $this->addSql('ALTER TABLE project ALTER COLUMN slug SET NOT NULL');
        $this->addSql('ALTER TABLE project ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE project ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX slug_unique ON project (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX slug_unique');
        $this->addSql('ALTER TABLE project DROP slug');
        $this->addSql('ALTER TABLE project ALTER id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE project ALTER id DROP IDENTITY');
    }
}
