FROM php:8.5-fpm-alpine

RUN apk add --no-cache \
    git \
    unzip \
    zip \
    libpng-dev \
    icu-dev \
    libzip-dev \
    libpq-dev \
    postgresql-client \
    nodejs \
    npm 
    
RUN docker-php-ext-install pdo_pgsql zip gd intl

### XDEBUG ####
RUN apk add --no-cache \
    linux-headers \
    autoconf \
    g++ \
    make

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY docker/xdebug/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
### XDEBUG ####

WORKDIR /var/www/portfolio

COPY web/ /var/www/portfolio

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-scripts
RUN chown -R www-data:www-data /var/www/portfolio

CMD ["php-fpm"]