<?php

namespace ContainerTXs4Fq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolver_UidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.argument_resolver.uid' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\UidValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ValueResolver'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ValueResolver'.\DIRECTORY_SEPARATOR.'UidValueResolver.php';

        return $container->privates['console.argument_resolver.uid'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\UidValueResolver();
    }
}
