name: "PR - Check Docker Build"
run-name: "Check Docker Build @${{ github.run_id }}"

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/buildDockerImage.yml
    with:
      push: false
