name: "↪️ Deploy VPS"
on:
  workflow_dispatch:
    inputs:
      ssh_host:
        description: "SSH Host"
        required: true
        default: "example.com"
      ssh_user:
        description: "SSH User"
        required: true
        default: "user"
      ssh_port:
        description: "SSH Port"
        required: false
        default: "22"
      ssh_key:
        description: "SSH Private Key (Base64 Encoded)"
        required: true
      ssh_passphrase:
        description: "SSH Key Passphrase (if any)"
        required: false

  workflow_run:
    workflows: [Build Docker Image]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: "⬇ Deploy On VPS"
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          timeout: 40m 
          command_timeout: 40m
          script: |
            cd /home/${{ secrets.VPS_USER }}/githubPortfolio
            export GITHUB_TOKEN="${{ secrets.PACKAGE_TOKEN }}"
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u Lurius-Kitsune --password-stdin
            git pull origin main
            npm install
            npm build
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
